### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [AnW0lf/VolkovEgorEducationProject#1]
1. Вы как-то сильно усложнили себе задание. Не очень понятно, зачем Вам понадобилась реализовывать собственную версию связанного списка. В любом случае, для реализации табличной функции лучше подходит `Map`, а не список, поскольку позволяет получать значение по ключу намного быстрее, чем полным перебором списка.
1. С интерполяцией Вы тоже перемудрили: не обязательно было брать сложную интерполяцию, вполне можно было обойтись линейной. Для линейной интерполяции, кстати, лучше использовать `TreeMap`.

**Comment by AnW0lf** [comment]
Доброго времени суток. Я уже давно переписал под TreeMap, только оставил интерполяцию Лагранжа, так как в простых функциях типа ax^n+b он учитывает изгиб. Можете мне тогда что-то ответить или дать 2 задание, я болел и физически не мог его получить на занятии.

**Comment by maximpetrov** [comment]
Вы использовали `TreeMap`, как обычный `Map`. У `TreeMap` есть методы, позволяющие получить максимальный элемент, минимальный элемент (без перевода в список), а также ближайший сверху или снизу.

**Comment by AnW0lf** [comment]
Удалил min(), max() и toLinkedList(). searchClosed() и interpolate() исправил, используя методы TreeMap.

**Comment by maximpetrov** [comment]
Предполагалось, что `searchClosed` с помощью методов `TreeMap` будет реализован без цикла.

**Comment by AnW0lf** [comment]
Реализовал searchClosed без цикла.
Вопрос по 2-му заданию. В условии сказано, что должна быть функция инвертирования условия поиска, но как она должно реально работать не описано. Что она должна делать?
Из строки "qwery ytrewq asdfgh hgfdsa" с условием поиска "не ytrewq", должно вывестись "qwery" и "asdfgh hgfdsa"? Или как?

**Comment by maximpetrov** [comment]
Ваша утилита по заданию должна выводить целиком строки, содержащие заданную подстроку. Соответственно, в режиме инвертирования условия, она должна выводить тоже целиком строки, не содержащие заданную подстроку.
